spring:
  datasource:
    url: jdbc:mysql://localhost:3306/concert_scenario
    username: root
    password: park0719!@#
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    properties:
      hibernate:
        type: debug

jwt:
  secretkey: 67CV7JiB7KSA7Iqk7ZSE66eB67aA7Yq47Iqk7YSw65SU

queue:
  max:
    size: 50

server:
  port: 9090